### ISSUE TITLE
ValueError: Selected block normalization method is invalid.

### ISSUE THREAD

**Issue by wiryawan46** [agungdwiprasetyo/image-pattern-recognition#1]
Ini kenapa ya pak?

> `Traceback (most recent call last):
  File "./start.py", line 10, in <module>
    EkstrakFitur().startExtract()
  File "/Volumes/DEV/ular_gigit/Riset2/image-pattern-recognition-master/mainClass/EkstrakFitur.py", line 48, in startExtract
    TrainingData(vektorObjek, vektorNonObjek).startTraining()
  File "/Volumes/DEV/ular_gigit/Riset2/image-pattern-recognition-master/mainClass/TrainCitra.py", line 58, in startTraining
    ConfusionMatrix(model=clf).printMatrix()
  File "/Volumes/DEV/ular_gigit/Riset2/image-pattern-recognition-master/mainClass/ConfusionMatrix.py", line 25, in printMatrix
    fitur = hog(img, orientations, cellSize, cellPerBlock, visualizeHOG, normalizeHOG)
  File "/usr/local/lib/python2.7/site-packages/skimage/feature/_hog.py", line 237, in hog
    _hog_normalize_block(block, method=block_norm)
  File "/usr/local/lib/python2.7/site-packages/skimage/feature/_hog.py", line 20, in _hog_normalize_block
    raise ValueError('Selected block normalization method is invalid.')
ValueError: Selected block normalization method is invalid.
`

**Comment by agungdwiprasetyo** [comment]
Resolusi citra data latihnya udah disamakan semua?

**Comment by wiryawan46** [comment]
belum pak, ukurannya pakai standar yang mana ya?

**Comment by agungdwiprasetyo** [comment]
pake ukuran 200x80 pixels (di readme.md)
